/*Parts of script generated by openAI ChatGPT March 2026*/
/* Grab references to key HTML elements by their IDs */
const btn = document.getElementById("loadBtn");
const container = document.getElementById("dataContainer");
const loading = document.getElementById("loadingMessage");
const error = document.getElementById("errorMessage");
/* Async function to load a joke */
async function loadJoke() {
  loading.style.display = "block";
  error.textContent = "";
  /*Fetch 10 jokes from the official joke API*/
  /* If the response is not ok it will throw an error*/
  /*Parse the response JSON into an array of joke objects*/
  try {
    const response = await fetch("https://official-joke-api.appspot.com/jokes/ten");
    if (!response.ok) throw new Error("Network error");
    const jokes = await response.json();

    // New Jokes that are on theme with the site!
    const extraJokes = [
      { setup: "Why did the trilobite cross the road?", punchline: "To get to the fossil shop!" },
      { setup: "Why was pre-cambrian era so quite?", punchline: "Because no one had the guts to make noise yet" },
      { setup: "Why did the ammonite get promoted?", punchline: "Because it was a spiral thinker!" }
    ];

    /*Merges API jokes with local ones*/
    /* Randomly pick one joke from the combined array*/
    const allJokes = [...jokes, ...extraJokes];
    const joke = allJokes[Math.floor(Math.random() * allJokes.length)];
    /* shows the selected joke inside the container as a card*/
    container.innerHTML = `
      <div class="fun-jokes-card">
        <strong>${joke.setup}</strong>
        <p>${joke.punchline}</p>
      </div>
    `;
    /*Show an error message if something goes wrong*/
  } catch (err) {
    error.textContent = "Oops! Could not load a joke.";
    /*Hide the loading message whether success or failure*/
  } finally {
    loading.style.display = "none";
  }
}
/* Attach click event listener to the button to trigger loadJoke */
btn.addEventListener("click", loadJoke);
