/*Parts of script generated by openAI ChatGPT May 2026*/
//Top button js controls
//scroll animation 
const topBtn = document.getElementById("topBtn");

if (topBtn) {

  window.addEventListener("scroll", () => {
    if (window.scrollY > 300) {
      topBtn.classList.add("show");
    } else {
      topBtn.classList.remove("show");
    }
  });

  topBtn.addEventListener("click", () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth"
    });
  });

}
